### ISSUE TITLE
Carris transit data

### ISSUE THREAD

**Issue by locosmac** [OneStopTransport/OneStopTransport#2]
I am experimenting with your gtfs data from Carris Lisboa and it seems to me that the data might have some issues. For example, if I compute the vehicle speed between two stops on a trip by using the areal distance between two stops as a crude estimate for the driving distance, the data set contains serveral stoptimes with speeds beyond 100 m/s. Below some examples:

Trip: 69176 Stoptime (Sequence) from 2 to 3 has a high speed (229.79860477862312 m/s).
Trip: 69176 Stoptime (Sequence) from 3 to 4 has a high speed (189.5251726627225 m/s).
Trip: 69342 Stoptime (Sequence) from 2 to 3 has a high speed (229.79860477862312 m/s).
Trip: 69342 Stoptime (Sequence) from 3 to 4 has a high speed (189.5251726627225 m/s).
Trip: 68752 Stoptime (Sequence) from 2 to 3 has a high speed (229.79860477862312 m/s).
Trip: 68752 Stoptime (Sequence) from 3 to 4 has a high speed (189.5251726627225 m/s).
Trip: 69474 Stoptime (Sequence) from 2 to 3 has a high speed (229.79860477862312 m/s).
Trip: 69474 Stoptime (Sequence) from 3 to 4 has a high speed (189.5251726627225 m/s).
Trip: 68920 Stoptime (Sequence) from 2 to 3 has a high speed (229.79860477862312 m/s).
Trip: 68920 Stoptime (Sequence) from 3 to 4 has a high speed (189.5251726627225 m/s).
Trip: 69594 Stoptime (Sequence) from 2 to 3 has a high speed (229.79860477862312 m/s).
Trip: 69594 Stoptime (Sequence) from 3 to 4 has a high speed (189.5251726627225 m/s).
Trip: 69056 Stoptime (Sequence) from 2 to 3 has a high speed (229.79860477862312 m/s).
Trip: 69056 Stoptime (Sequence) from 3 to 4 has a high speed (189.5251726627225 m/s). 

As a result of these issues, the trip durations of several trips are too short. For example, the data set contains trips with line 732 stating that it is possible to get from Caselas to Conde Barao in 10 minutes. Google Transit estimates the duration for this trip with 32 minutes.

**Comment by rjvitorino** [comment]
Hello @locosmac and thank you for this issue! Unfortunately, data about Carris is very outdated, thus, we're making an effort to get more recent data and update it. I'll keep you posted.

**Comment by locosmac** [comment]
@rjfv that sounds great, thank you very much!
