### ISSUE TITLE
Coimbra GTFS

### ISSUE THREAD

**Issue by andredelgado** [OneStopTransport/OneStopTransport#3]
Coimbra GTFS is outdated.

**Comment by rjvitorino** [comment]
Work in progress, sorry for the delay.

**Comment by andredelgado** [comment]
Any update? @rjfv

**Comment by rjvitorino** [comment]
There is an issue on SMTUC's data which has already been reported, we're waiting for an updated version from them. Sorry for the delay and thank you very much for your attention on this subject.

**Comment by rjvitorino** [comment]
@andredelgado I'm so sorry for the delay! Datasets have been corrected by the agency and are now being published. Tomorrow morning everything will be back to normal. Thank you for your patience and please accept my apologies for the huge delay.

**Comment by andredelgado** [comment]
Thank you for the update @rjfv
